zone_bounds:
 - zone_name: zone_1
   x_min: 0.4
   x_max: 0.8
   y_min: -0.32
   y_max: 0.1
   next_location_gen_mode: 1
 - zone_name: zone_2
   x_min: 0.4
   x_max: 0.8
   y_min: 0.1
   y_max: 0.4
   next_location_gen_mode: 0
place_zone:
  frame_id: base_link
  pose_candidates: 8
  orientation_axis:
    x: 0
    y: 0
    z: 1
  release_distance: 0.02
  next_location:
    min_spacing: 0.16
    max_spacing: 0.20
