pick_zones:
 - zone_name: singulated_zone
   x_min: -0.325
   x_max: 0.325
   y_min: 0.25
   y_max: 0.72
   frame_id: workcell_frame
#___________________________________#
 - zone_name: clutter_zone
   x_min: -1.0
   x_max: -0.5
   y_min: -0.60
   y_max: 0.60
   frame_id: workcell_frame
place_zones:
 - zone_name: place_clutter_zone
   x_min: -1.0
   x_max: -0.5
   y_min: -0.60
   y_max: 0.60
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.001
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [0, 1, 2, 3, 4, 5]

