multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: workcell_frame
    child_frame_id: workcell_frame
groups:
  - name: ur5_arm
    base_link: ur5_arm/base_link
    tip_link: ur5_arm/ee_link
  - name: ur5_gripper
    joints:
      - ur5_to_gripper
      - ur5_arm/gripper_to_tcp
default_collision_operations:
  - object1: workcell_frame
    object2: ur5_arm/kinect
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/kinect_frame
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/kinect_ir_optical_frame
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_arm/kinect_rgb_optical_frame
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: ur5_arm/kinect_keepout
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: back_wall2
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: cover_part1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: cover_part2
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: front_wall2
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: left_wall2
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: right_wall2
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: ur5_stand
    operation: disable  # Adjacent in collision
  - object1: ur5_stand
    object2: ur5_arm/base_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/base_link
    object2: ur5_arm/shoulder_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/shoulder_link
    object2: ur5_arm/upper_arm_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/upper_arm_link
    object2: ur5_arm/forearm_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/forearm_link
    object2: ur5_arm/wrist_1_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/wrist_1_link
    object2: ur5_arm/wrist_2_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/wrist_2_link
    object2: ur5_arm/wrist_3_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/wrist_3_link
    object2: ur5_arm/ee_link
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/ee_link
    object2: ur5_arm/gripper_frame
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/gripper_frame
    object2: ur5_arm/gripper_body
    operation: disable  # Adjacent in collision
  - object1: ur5_arm/gripper_frame
    object2: ur5_arm/tcp_frame
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: table_base2
    operation: disable  # Adjacent in collision
  - object1: back_wall2
    object2: cover_part1
    operation: disable  # Always in collision
  - object1: back_wall2
    object2: cover_part2
    operation: disable  # Always in collision
  - object1: back_wall2
    object2: left_wall2
    operation: disable  # Always in collision
  - object1: back_wall2
    object2: right_wall2
    operation: disable  # Always in collision
  - object1: back_wall2
    object2: table_base2
    operation: disable  # Always in collision
  - object1: cover_part1
    object2: cover_part2
    operation: disable  # Always in collision
  - object1: cover_part1
    object2: table_base2
    operation: disable  # Always in collision
  - object1: cover_part2
    object2: table_base2
    operation: disable  # Always in collision
  - object1: front_wall2
    object2: left_wall2
    operation: disable  # Always in collision
  - object1: front_wall2
    object2: right_wall2
    operation: disable  # Always in collision
  - object1: front_wall2
    object2: table_base2
    operation: disable  # Always in collision
  - object1: front_wall2
    object2: ur5_arm/kinect
    operation: disable  # Always in collision
  - object1: front_wall2
    object2: ur5_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: left_wall2
    object2: table_base2
    operation: disable  # Always in collision
  - object1: right_wall2
    object2: table_base2
    operation: disable  # Always in collision
  - object1: table_base2
    object2: ur5_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect_keepout
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Always in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/forearm_link
    operation: disable  # Default in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/wrist_2_link
    operation: disable  # Default in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/wrist_1_link
    operation: disable  # Default in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/wrist_2_link
    operation: disable  # Occasionally in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/wrist_3_link
    operation: disable  # Occasionally in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/kinect
    operation: disable  # Occasionally in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/kinect_frame
    operation: disable  # Occasionally in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/wrist_3_link
    operation: disable  # Occasionally in collision
  - object1: back_wall2
    object2: front_wall2
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: back_wall2
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: front_wall2
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: left_wall2
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: right_wall2
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: cover_part1
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: front_wall2
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: left_wall2
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: right_wall2
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: cover_part2
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/forearm_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/gripper_body
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/wrist_1_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/wrist_2_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_arm/wrist_3_link
    operation: disable  # Never in collision
  - object1: front_wall2
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: right_wall2
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: left_wall2
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: right_wall2
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_arm/base_link
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: table_base2
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/base_link
    object2: ur5_arm/kinect
    operation: disable  # Never in collision
  - object1: ur5_arm/base_link
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: ur5_arm/base_link
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: ur5_arm/base_link
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: ur5_arm/base_link
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: ur5_arm/forearm_link
    object2: ur5_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: ur5_arm/forearm_link
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: ur5_arm/forearm_link
    object2: ur5_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: ur5_arm/forearm_link
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/wrist_1_link
    operation: disable  # Never in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/wrist_2_link
    operation: disable  # Never in collision
  - object1: ur5_arm/gripper_body
    object2: ur5_arm/wrist_3_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_arm/wrist_1_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_frame
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/wrist_1_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/wrist_2_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_arm/wrist_3_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_ir_link
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_keepout
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_keepout
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_keepout
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_arm/shoulder_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_arm/upper_arm_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_arm/wrist_1_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_arm/wrist_2_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_arm/wrist_3_link
    operation: disable  # Never in collision
  - object1: ur5_arm/kinect_rgb_link
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/shoulder_link
    object2: ur5_stand
    operation: disable  # Never in collision
  - object1: ur5_arm/wrist_1_link
    object2: ur5_arm/wrist_3_link
    operation: disable  # Never in collision