navigator:
  arm_group: ur5_arm
  gripper_group: ur5_gripper
  wrist_link: ur5_arm_ee_link
  gripper_link: ur5_arm_tcp_frame
  planner_service_name: /ur5_arm/path_planning/plan_kinematic_path
  trajectory_filter_service_name: /ur5_arm/trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: /ur5_arm/tabletop_segmentation
  recognition_service_name: /ur5_arm/mantis_object_recognition
  grasp_planning_service_name: /ur5_arm/plan_point_cluster_grasp
  planning_scene_service_name: /ur5_arm/environment_server/set_planning_scene_diff
  arm_inverse_kinematics_plugin: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  joint_state_topic: /ur5_arm/joint_states
  joint_trajectory_service_name: /ur5_arm/joint_trajectory_action
  grasp_action_service_name: /ur5_arm/grasp_execution_action
segmentation:
  world_frame_id: workcell_frame
  k_nearest: 40
  max_iterations: 400
  sac_method: 6 #ransac = 0
  normal_distance_weight: 0.2
  distance_threshold: 0.0005
  max_radius: 0.028
  min_fitness_score: 20 # minimum number of inliers
  align_to_top_centroid: true
joints:
  side_position: [-1.51, -1.07948096023743, 1.7135035147002855, -2.2049080765129627, -1.57158764211257, -1.6830470243995475]
