pick_zones:
 - zone_name: zone_a
   x_min: -1.2
   x_max: -0.6
   y_min: -1.0
   y_max: 0.0
   frame_id: workcell_frame
 - zone_name: zone_b
   x_min: -1.2
   x_max: -0.6
   y_min: 0.01
   y_max: 0.8
   frame_id: workcell_frame
place_zones:
 - zone_name: place_zone_a_1
   x_min: -1.2
   x_max: -0.6
   y_min: -1.0
   y_max: -0.51
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [1,3,5]
 - zone_name: place_zone_a_2
   x_min: -1.2
   x_max: -0.6
   y_min: -0.50
   y_max: -0.01
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [0,2]
 - zone_name: place_zone_b_1
   x_min: -1.2
   x_max: -0.882
   y_min: 0.01
   y_max: 0.8
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [1, 3, 5]
 - zone_name: place_zone_b_2
   x_min: -0.88
   x_max: -0.6
   y_min: 0.01
   y_max: 0.4
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [2]
 - zone_name: place_zone_b_4
   x_min: -0.88
   x_max: -0.6
   y_min: 0.401
   y_max: 0.8
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.025
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [0, 4]
