navigator:
  arm_group: ur5_arm
  gripper_group: ur5_gripper
  wrist_link: ur5_arm_ee_link
  gripper_link: ur5_arm_tcp_frame
  planner_service_name: /ur5_arm/path_planning/plan_kinematic_path
  trajectory_filter_service_name: /ur5_arm/trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: /ur5_arm/tabletop_segmentation
  recognition_service_name: /ur5_arm/mantis_object_recognition
  grasp_planning_service_name: /ur5_arm/plan_point_cluster_grasp
  planning_scene_service_name: /ur5_arm/environment_server/set_planning_scene_diff
  arm_inverse_kinematics_plugin: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
#  arm_inverse_kinematics_plugin: ur5_ur5_manipulator_kinematics/IKFastKinematicsPlugin
  joint_state_topic: /ur5_arm/joint_states
  joint_trajectory_service_name: /ur5_arm/joint_trajectory_action
  grasp_action_service_name: /ur5_arm/grasp_execution_action
  num_of_grasp_attempts: 4
  new_grasp_attempt_offset: 0.025 #1cm
  attached_object_bb_side: 0.1 #10cm
cluttered_dropoff:
  frame_id: workcell_frame
  position:
    x: -0.8
    y: 0.01
    z: 0.16
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0.7
  next_location:
    generation_mode: 0
singulated_dropoff:
  frame_id: workcell_frame
  position:
    x: 0.25
    y: 0.65
    z: 0.10
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0.7
  next_location:
    generation_mode: 0
joint_home_position:
  side_position: [1.6, -1.07948096023743, 1.7135035147002855, -2.2049080765129627, -1.57158764211257, -0.48]

