pick_zones:
 - zone_name: singulated_zone
   x_min: -0.84
   x_max: -0.5
   y_min: -0.65
   y_max: 0.0
   frame_id: workcell_frame
 - zone_name: sorted_zone
   x_min: -0.84
   x_max: -0.5
   y_min: 0.01
   y_max: 0.65
   frame_id: workcell_frame
place_zones:
 - zone_name: place_zone_a_1
   x_min: -0.84
   x_max: -0.5
   y_min: -0.65
   y_max: -0.281
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.001
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [1,3,5]
 - zone_name: place_zone_a_2
   x_min: -0.84
   x_max: -0.5
   y_min: -0.28
   y_max: -0.01
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.001
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [0,2]
 - zone_name: place_zone_b_1
   x_min: -0.84
   x_max: -0.701
   y_min: 0.00
   y_max: 0.65
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.001
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 1
   ids_allowed: [1, 3, 5]
 - zone_name: place_zone_b_2
   x_min: -0.70
   x_max: -0.5
   y_min: 0.00
   y_max: 0.65
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.001
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 1
   ids_allowed: [2, 4]
