service_type: FilterJointTrajectoryWithConstraints
filter_chain:
  -
    name: unnormalize_trajectory
    type: UnNormalizeFilterJointTrajectoryWithConstraints
  -
    name: cubic_spline_short_cutter_smoother
    type: CubicSplineShortCutterFilterJointTrajectoryWithConstraints
    params: {discretization: 0.02}
  -
    name: iterative_parabolic_smoother
    type: IterativeParabolicSmootherFilterJointTrajectoryWithConstraints
    params: {max_iterations: 1000, max_time_change_per_it: 0.001}
#  -
#    name: n_point_filter
#    type: NPointFilterJointTrajectoryWithConstraints
#    params: {n_points: 100}
