COPY byte_array.h ..\..\..\simple_message\include\simple_message\byte_array.h
COPY log_wrapper.h ..\..\..\simple_message\include\simple_message\log_wrapper.h
COPY shared_types.h ..\..\..\simple_message\include\simple_message\shared_types.h
COPY simple_message.h ..\..\..\simple_message\include\simple_message\simple_message.h
COPY simple_serialize.h ..\..\..\simple_message\include\simple_message\simple_serialize.h
COPY smpl_msg_connection.h ..\..\..\simple_message\include\simple_message\smpl_msg_connection.h
COPY message_handler.h ..\..\..\simple_message\include\simple_message\message_handler.h
COPY ping_message.h ..\..\..\simple_message\include\simple_message\ping_message.h
COPY ping_handler.h ..\..\..\simple_message\include\simple_message\ping_handler.h
COPY joint_data.h ..\..\..\simple_message\include\simple_message\joint_data.h
COPY message_manager.h ..\..\..\simple_message\include\simple_message\message_manager.h
COPY typed_message.h ..\..\..\simple_message\include\simple_message\typed_message.h
COPY comms_fault_handler.h ..\..\..\simple_message\include\simple_message\comms_fault_handler.h
COPY simple_comms_fault_handler.h ..\..\..\simple_message\include\simple_message\simple_comms_fault_handler.h
COPY byte_array.cpp ..\..\..\simple_message\src\byte_array.cpp
COPY simple_message.cpp ..\..\..\simple_message\src\simple_message.cpp
COPY smpl_msg_connection.cpp ..\..\..\simple_message\src\smpl_msg_connection.cpp
COPY message_handler.cpp ..\..\..\simple_message\src\message_handler.cpp
COPY ping_message.cpp ..\..\..\simple_message\src\ping_message.cpp
COPY ping_handler.cpp ..\..\..\simple_message\src\ping_handler.cpp
COPY joint_data.cpp ..\..\..\simple_message\src\joint_data.cpp
COPY message_manager.cpp ..\..\..\simple_message\src\message_manager.cpp
COPY simple_comms_fault_handler.cpp ..\..\..\simple_message\src\simple_comms_fault_handler.cpp
COPY simple_socket.h ..\..\..\simple_message\include\simple_message\socket\simple_socket.h
COPY tcp_socket.h ..\..\..\simple_message\include\simple_message\socket\tcp_socket.h
COPY tcp_client.h ..\..\..\simple_message\include\simple_message\socket\tcp_client.h
COPY tcp_server.h ..\..\..\simple_message\include\simple_message\socket\tcp_server.h
COPY udp_socket.h ..\..\..\simple_message\include\simple_message\socket\udp_socket.h
COPY udp_client.h ..\..\..\simple_message\include\simple_message\socket\udp_client.h
COPY udp_server.h ..\..\..\simple_message\include\simple_message\socket\udp_server.h
COPY simple_socket.cpp ..\..\..\simple_message\src\socket\simple_socket.cpp
COPY tcp_socket.cpp ..\..\..\simple_message\src\socket\tcp_socket.cpp
COPY tcp_client.cpp ..\..\..\simple_message\src\socket\tcp_client.cpp
COPY tcp_server.cpp ..\..\..\simple_message\src\socket\tcp_server.cpp
COPY udp_socket.cpp ..\..\..\simple_message\src\socket\udp_socket.cpp
COPY udp_client.cpp ..\..\..\simple_message\src\socket\udp_client.cpp
COPY udp_server.cpp ..\..\..\simple_message\src\socket\udp_server.cpp
COPY joint_message.h ..\..\..\simple_message\include\simple_message\messages\joint_message.h
COPY joint_message.cpp ..\..\..\simple_message\src\messages\joint_message.cpp
COPY mp_default_main.cpp ..\motoros_lib\mp_default_main.cpp
COPY mp_default_main.h ..\motoros_lib\mp_default_main.h
COPY joint_motion_handler.cpp ..\motoros_lib\joint_motion_handler.cpp
COPY joint_motion_handler.h ..\motoros_lib\joint_motion_handler.h
COPY input_handler.cpp ..\motoros_lib\input_handler.cpp
COPY input_handler.h ..\motoros_lib\input_handler.h
COPY motoros_lib.h ..\motoros_lib\motoros_lib.h
COPY mp_wrapper.cpp ..\motoros_lib\mp_wrapper.cpp
COPY mp_wrapper.h ..\motoros_lib\mp_wrapper.h
COPY p_var_q.cpp ..\motoros_lib\p_var_q.cpp
COPY p_var_q.h ..\motoros_lib\p_var_q.h
COPY ros_conversion.h ..\..\include\motoman\ros_conversion.h
COPY ros_conversion.cpp ..\..\src\ros_conversion.cpp
