
# ----- Arm -----
arm_chain:
  settler_config:  /arm_chain/settler_config

  configs:
    tight_tol:
      settler:
        joint_names:
        - joint_s
        - joint_l
        - joint_e
        - joint_u
        - joint_r
        - joint_b
        - joint_t
        tolerances:
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        - 0.002
        max_step:   1.0
        cache_size: 1500
