pick_zones:
 - zone_name: pick_zone1
   x_min: 0.2
   x_max: 1.6
   y_min: -1.2
   y_max: 0.0
   frame_id: base_link
 - zone_name: pick_zone2
   x_min: 0.2
   x_max: 1.6
   y_min: 0.0
   y_max: 1.2
   frame_id: base_link
# - zone_name: zone_1
#   x_min: 1.0
#   x_max: 1.4
#   y_min: 1.0
#   y_max: 1.5
#   next_location_gen_mode: 1
# - zone_name: zone_2
#   x_min: 1.5
#   x_max: 4.0
#   y_min: 1.1
#   y_max: 1.4
#   next_location_gen_mode: 0
place_zones:
 - zone_name: place_zone1
   x_min: 0.2
   x_max: 0.8
   y_min: -1.2
   y_max: 0.0
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [1, 2, 4, 8]
 - zone_name: place_zone2
   x_min: 0.8
   x_max: 1.6
   y_min: -1.2
   y_max: 0.0
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [3, 6, 10]
 - zone_name: place_zone3
   x_min: 0.2
   x_max: 0.8
   y_min: 0.0
   y_max: 1.2
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [1, 2]
 - zone_name: place_zone4
   x_min: 0.8
   x_max: 1.2
   y_min: 0.0
   y_max: 1.2
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [3, 6]
 - zone_name: place_zone5
   x_min: 1.2
   x_max: 1.6
   y_min: 0.0
   y_max: 1.0
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [4, 8]
 - zone_name: place_zone6
   x_min: 1.2
   x_max: 1.6
   y_min: 1.0
   y_max: 1.4
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [10]
