pick_zones:
 - zone_name: pick_zone1
   x_min: 0.2
   x_max: 1.6
   y_min: -1.2
   y_max: 0.0
   frame_id: base_link
 - zone_name: pick_zone2
   x_min: 0.2
   x_max: 1.6
   y_min: 0.01
   y_max: 1.2
   frame_id: base_link
place_zones:
 - zone_name: place_zone1
   x_min: 0.2
   x_max: 1.6
   y_min: -1.2
   y_max: 0.0
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.08
    max_spacing: 0.10
    generation_mode: 1
   ids_allowed: [3, 6, 10, 1, 2, 4, 8]
 - zone_name: place_zone2
   x_min: 0.2
   x_max: 1.0
   y_min: 0.01
   y_max: 1.2
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.08
    max_spacing: 0.12
    generation_mode: 4
   ids_allowed: [3, 6, 10]
 - zone_name: place_zone4
   x_min: 1.01
   x_max: 1.60
   y_min: 0.60
   y_max: 1.05
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.08
    max_spacing: 0.12
    generation_mode: 0
   ids_allowed: [1, 2, 4, 8]
 - zone_name: place_zone5
   x_min: 0.40
   x_max: 1.40
   y_min: 1.28
   y_max: 1.60
   frame_id: base_link
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.02
   next_location:
    min_spacing: 0.08
    max_spacing: 0.12
    generation_mode: 2
   ids_allowed: [3, 6, 10, 1, 2, 4, 8]
