pick_zones:
 - zone_name: singulated_zone
   x_min: -0.10
   x_max: 0.350
   y_min: 0.25
   y_max: 0.80
   frame_id: workcell_frame
#___________________________________#
 - zone_name: sorted_zone
   x_min: 0.50
   x_max: 1.2
   y_min: -0.7
   y_max: 0.80
   frame_id: workcell_frame
place_zones:
#___________________________________#
 - zone_name: sort_zone_1
   x_min: 0.6
   x_max: 1.0
   y_min: 0.301
   y_max: 0.70
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.01
   next_location:
    min_spacing: 0.20
    max_spacing: 0.22
    generation_mode: 2
   ids_allowed: [0, 4, 5]
   objs_allowed: [CAPS]
#___________________________________#
 - zone_name: sort_zone_2
   x_min: 0.6
   x_max: 1.0
   y_min: -0.10
   y_max: 0.30
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.01
   next_location:
    min_spacing: 0.20
    max_spacing: 0.22
    generation_mode: 2
   ids_allowed: [3]
   objs_allowed: [TEES]
#___________________________________#
 - zone_name: sort_zone_3
   x_min: 0.6
   x_max: 1.0
   y_min: -0.48
   y_max: -0.101
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.01
   next_location:
    min_spacing: 0.20
    max_spacing: 0.22
    generation_mode: 1
   ids_allowed: [1] 
   objs_allowed: [BOXES]
