navigator:
######################### ros topic and services parameters #######################
  arm_group: sia20d_arm
  gripper_group: sia20d_gripper
  wrist_link: sia20d_arm_link_t
  gripper_link: sia20d_arm_tcp_frame
  planner_service_name: /sia20d_arm/path_planning/plan_kinematic_path
  trajectory_filter_service_name: /sia20d_arm/trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: /sia20d_arm/tabletop_segmentation
  singulation_segmentation_service_name: /sia20d_arm/singulation/tabletop_segmentation
  recognition_service_name: /sia20d_arm/mantis_object_recognition
  grasp_planning_service_name: /sia20d_arm/plan_point_cluster_grasp
  planning_scene_service_name: /sia20d_arm/environment_server/set_planning_scene_diff
  arm_inverse_kinematics_plugin: SIA20D_Mesh_manipulator_kinematics/IKFastKinematicsPlugin
  joint_state_topic: /sia20d_arm/joint_states
  joint_trajectory_service_name: /sia20d_arm/joint_trajectory_action
  grasp_action_service_name: /sia20d_arm/grasp_execution_action
######################### grasp pick and place parameters ########################
  pick_approach_distance: 0.1
  place_approach_distance: 0.1
  place_retreat_distance: 0.1
########################## grasp pick retry parameters ##########################
  pick_retry_attempts: 8
  pick_retry_offset: 0.03 # cm
  pick_retry_retreat_distance: 0.05
  attached_object_bb_side: 0.1 # 10cm
############################ place zone parameter ###############################
  attached_object_bb_side: 0.1 # 10cm
  singulation_zone_index: 0
  cluttered_zone_index: 1
  sorted_zone_index: 1
cluttered_dropoff:
#  frame_id: sia20d_arm_base_link
  frame_id: workcell_frame
  position:
    x: 0.8
    y: 0.01
    z: 0.1
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0.7
  next_location:
    generation_mode: 0
    min_spacing: 0.05 # meters (ignored if using generation mode 0)
    max_spacing: 0.08 # meters (ignored if using generation mode 0)
    place_region_radius: 0.2 # meters (ignored if using generation mode 0)
singulated_dropoff:
#  frame_id: sia20d_arm_base_link
  frame_id: workcell_frame
  position:
    x: -0.36
    y: 0.55
    z: 0.07
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0.7
  next_location:
    generation_mode: 0
    min_spacing: 0.05 # meters (ignored if using generation mode 0)
    max_spacing: 0.08 # meters (ignored if using generation mode 0)
    place_region_radius: 0.2 # meters (ignored if using generation mode 0)
joint_home_position:
  side_position: [-0.90, 0.68, 2.46, 1.25, -0.41, 1.34,1.14]
