main:
  planner_service_name: /path_planning/plan_kinematic_path
  trajectory_filter_service_name: /trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: /tabletop_segmentation
  grasp_planning_service_name: /plan_point_cluster_grasp
  planning_scene_service_name: /environment_server/set_planning_scene_diff
  recognition_service_name: /tabletop_object_recognition
  mesh_database_service_name: /objects_database_node/get_model_mesh
  model_database_service_name: /objects_database_node/get_model_description
  arm_inverse_kinematics_plugin: SIA20D_Mesh_manipulator_kinematics/IKFastKinematicsPlugin
