multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: manipulator
    base_link: base_link
    tip_link: palm
  - name: end_effector
    joints:
      - joint_1
      - joint_2
      - joint_3
      - tool-coupler
      - coupler-hand
default_collision_operations:
  - object1: base_link
    object2: controller
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: filter
    operation: disable  # Adjacent in collision
  - object1: filter
    object2: kinect
    operation: disable  # Adjacent in collision
  - object1: kinect
    object2: kinect_frame
    operation: disable  # Adjacent in collision
  - object1: kinect_frame
    object2: kinect_ir_link
    operation: disable  # Adjacent in collision
  - object1: kinect_ir_link
    object2: kinect_ir_optical_frame
    operation: disable  # Adjacent in collision
  - object1: kinect_ir_link
    object2: kinect_rgb_link
    operation: disable  # Adjacent in collision
  - object1: kinect_rgb_link
    object2: kinect_rgb_optical_frame
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: pallet
    operation: disable  # Adjacent in collision
  - object1: pallet
    object2: floor
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: tables
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: link_s
    operation: disable  # Adjacent in collision
  - object1: link_s
    object2: link_l
    operation: disable  # Adjacent in collision
  - object1: link_l
    object2: link_e
    operation: disable  # Adjacent in collision
  - object1: link_e
    object2: link_u
    operation: disable  # Adjacent in collision
  - object1: link_u
    object2: link_r
    operation: disable  # Adjacent in collision
  - object1: link_r
    object2: link_b
    operation: disable  # Adjacent in collision
  - object1: link_b
    object2: link_t
    operation: disable  # Adjacent in collision
  - object1: link_t
    object2: coupler
    operation: disable  # Adjacent in collision
  - object1: coupler
    object2: palm
    operation: disable  # Adjacent in collision
  - object1: palm
    object2: finger_1
    operation: disable  # Adjacent in collision
  - object1: palm
    object2: finger_2
    operation: disable  # Adjacent in collision
  - object1: palm
    object2: finger_3
    operation: disable  # Adjacent in collision
  - object1: floor
    object2: tables
    operation: disable  # Always in collision
  - object1: kinect
    object2: kinect_ir_link
    operation: disable  # Always in collision
  - object1: kinect
    object2: kinect_rgb_link
    operation: disable  # Always in collision
  - object1: kinect_frame
    object2: kinect_rgb_link
    operation: disable  # Always in collision
  - object1: base_link
    object2: floor
    operation: disable  # Never in collision
  - object1: base_link
    object2: link_e
    operation: disable  # Never in collision
  - object1: base_link
    object2: link_l
    operation: disable  # Never in collision
  - object1: controller
    object2: filter
    operation: disable  # Never in collision
  - object1: controller
    object2: floor
    operation: disable  # Never in collision
  - object1: controller
    object2: link_l
    operation: disable  # Never in collision
  - object1: controller
    object2: link_s
    operation: disable  # Never in collision
  - object1: controller
    object2: pallet
    operation: disable  # Never in collision
  - object1: coupler
    object2: finger_1
    operation: disable  # Never in collision
  - object1: coupler
    object2: finger_2
    operation: disable  # Never in collision
  - object1: coupler
    object2: finger_3
    operation: disable  # Never in collision
  - object1: coupler
    object2: link_b
    operation: disable  # Never in collision
  - object1: coupler
    object2: link_e
    operation: disable  # Never in collision
  - object1: coupler
    object2: link_r
    operation: disable  # Never in collision
  - object1: coupler
    object2: link_u
    operation: disable  # Never in collision
  - object1: filter
    object2: floor
    operation: disable  # Never in collision
  - object1: filter
    object2: link_l
    operation: disable  # Never in collision
  - object1: filter
    object2: link_s
    operation: disable  # Never in collision
  - object1: filter
    object2: pallet
    operation: disable  # Never in collision
  - object1: finger_1
    object2: finger_2
    operation: disable  # Never in collision
  - object1: finger_1
    object2: finger_3
    operation: disable  # Never in collision
  - object1: finger_1
    object2: link_b
    operation: disable  # Never in collision
  - object1: finger_1
    object2: link_e
    operation: disable  # Never in collision
  - object1: finger_1
    object2: link_r
    operation: disable  # Never in collision
  - object1: finger_1
    object2: link_t
    operation: disable  # Never in collision
  - object1: finger_1
    object2: link_u
    operation: disable  # Never in collision
  - object1: finger_2
    object2: finger_3
    operation: disable  # Never in collision
  - object1: finger_2
    object2: link_b
    operation: disable  # Never in collision
  - object1: finger_2
    object2: link_e
    operation: disable  # Never in collision
  - object1: finger_2
    object2: link_r
    operation: disable  # Never in collision
  - object1: finger_2
    object2: link_t
    operation: disable  # Never in collision
  - object1: finger_2
    object2: link_u
    operation: disable  # Never in collision
  - object1: finger_3
    object2: link_b
    operation: disable  # Never in collision
  - object1: finger_3
    object2: link_e
    operation: disable  # Never in collision
  - object1: finger_3
    object2: link_r
    operation: disable  # Never in collision
  - object1: finger_3
    object2: link_t
    operation: disable  # Never in collision
  - object1: finger_3
    object2: link_u
    operation: disable  # Never in collision
  - object1: floor
    object2: link_e
    operation: disable  # Never in collision
  - object1: floor
    object2: link_l
    operation: disable  # Never in collision
  - object1: floor
    object2: link_r
    operation: disable  # Never in collision
  - object1: floor
    object2: link_s
    operation: disable  # Never in collision
  - object1: floor
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_b
    object2: link_e
    operation: disable  # Never in collision
  - object1: link_b
    object2: link_l
    operation: disable  # Never in collision
  - object1: link_b
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_b
    object2: palm
    operation: disable  # Never in collision
  - object1: link_e
    object2: link_r
    operation: disable  # Never in collision
  - object1: link_e
    object2: link_s
    operation: disable  # Never in collision
  - object1: link_e
    object2: link_t
    operation: disable  # Never in collision
  - object1: link_e
    object2: pallet
    operation: disable  # Never in collision
  - object1: link_e
    object2: palm
    operation: disable  # Never in collision
  - object1: link_l
    object2: link_r
    operation: disable  # Never in collision
  - object1: link_l
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_l
    object2: pallet
    operation: disable  # Never in collision
  - object1: link_r
    object2: link_t
    operation: disable  # Never in collision
  - object1: link_r
    object2: palm
    operation: disable  # Never in collision
  - object1: link_s
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_s
    object2: pallet
    operation: disable  # Never in collision
  - object1: link_t
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_t
    object2: palm
    operation: disable  # Never in collision
  - object1: link_u
    object2: pallet
    operation: disable  # Never in collision
  - object1: link_u
    object2: palm
    operation: disable  # Never in collision