

- name: "Narrow L Stereo: Right Arm"
  3d: right_arm_chain
  cam: narrow_left_rect
  plot_ops:
    color: g
    marker: s
- name: "Narrow R Stereo: Right Arm"
  3d: right_arm_chain
  cam: narrow_right_rect
  plot_ops:
    color: g
    marker: o

- name: "Wide L Stereo: Right Arm"
  3d: right_arm_chain
  cam: wide_left_rect
  plot_ops:
    color: y
    marker: s
- name: "Wide R Stereo: Right Arm"
  3d: right_arm_chain
  cam: wide_right_rect
  plot_ops:
    color: y
    marker: o

- name: "Narrow L Stereo: Left Arm"
  3d: left_arm_chain
  cam: narrow_left_rect
  plot_ops:
    color: m
    marker: s
- name: "Narrow R Stereo: Left Arm"
  3d: left_arm_chain
  cam: narrow_right_rect
  plot_ops:
    color: m
    marker: o

- name: "Wide L Stereo: Left Arm"
  3d: left_arm_chain
  cam: wide_left_rect
  plot_ops:
    color: c
    marker: s
- name: "Wide R Stereo: Left Arm"
  3d: left_arm_chain
  cam: wide_right_rect
  plot_ops:
    color: c
    marker: o

- name: "Prosilica: Left Arm"
  3d: left_arm_chain
  cam: prosilica_rect
  plot_ops:
    color: r
    marker: o

- name: "Prosilica: Right Arm"
  3d: right_arm_chain
  cam: prosilica_rect
  plot_ops:
    color: r
    marker: s
