COPY motoros_lib.mpLib ..\..\..\motoman\dx100\motoplus\motoros_lib\output\motoros_lib.mpLib
COPY motoros_lib.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\motoros_lib.h
COPY byte_array.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\byte_array.h
COPY log_wrapper.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\log_wrapper.h
COPY message_handler.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\message_handler.h
COPY shared_types.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\shared_types.h
COPY simple_message.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_message.h
COPY simple_serialize.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_serialize.h
COPY simple_socket.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_socket.h
COPY smpl_msg_connection.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\smpl_msg_connection.h
COPY tcp_server.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\tcp_server.h
COPY tcp_socket.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\tcp_socket.h
COPY typed_message.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\typed_message.h
COPY comms_fault_handler.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\comms_fault_handler.h
COPY joint_data.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_data.h
COPY message_manager.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\message_manager.h
COPY mp_default_main.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\mp_default_main.h
COPY ping_handler.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\ping_handler.h
COPY ros_conversion.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\ros_conversion.h
COPY simple_comms_fault_handler.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_comms_fault_handler.h
COPY joint_traj.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_traj.h
COPY trajectory_job.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\trajectory_job.h
COPY joint_traj_pt.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_traj_pt.h
COPY joint_traj_pt_message.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_traj_pt_message.h
COPY controller.h ..\..\..\motoman\dx100\motoplus\motoros_lib\output\controller.h
COPY armadillo.h ..\include\armadillo\armadillo.h
COPY gripper_message.h ..\include\armadillo\messages\gripper_message.h
COPY gripper_message.cpp ..\src\gripper_message.cpp
