r_arm_controller:
  topic: r_arm_controller/command
  joint_names:
  - r_shoulder_pan_joint
  - r_shoulder_lift_joint
  - r_upper_arm_roll_joint
  - r_elbow_flex_joint
  - r_forearm_roll_joint
  - r_wrist_flex_joint
  - r_wrist_roll_joint

l_arm_controller:
  topic: l_arm_controller/command
  joint_names:
  - l_shoulder_pan_joint
  - l_shoulder_lift_joint
  - l_upper_arm_roll_joint
  - l_elbow_flex_joint
  - l_forearm_roll_joint
  - l_wrist_flex_joint
  - l_wrist_roll_joint

head_traj_controller:
  topic: head_traj_controller/command
  joint_names:
  - head_pan_joint
  - head_tilt_joint
