joint_trajectory_action:
  joints:
    - ur5_arm_shoulder_pan_joint
    - ur5_arm_shoulder_lift_joint
    - ur5_arm_elbow_joint
    - ur5_arm_wrist_1_joint
    - ur5_arm_wrist_2_joint
    - ur5_arm_wrist_3_joint
  constraints:
    goal_time: 0.3
    ur5_arm_shoulder_pan_join:
      goal: 0.04
    ur5_arm_shoulder_lift_joint:
      goal: 0.04
    ur5_arm_elbow_joint:
      goal: 0.04
    ur5_arm_wrist_1_joint:
      goal: 0.04
    ur5_arm_wrist_2_joint:
      goal: 0.04
    ur5_arm_wrist_3_joint:
      goal: 0.04
