navigator:
# ######################## ros topic and services parameters #######################
  arm_group: ur5_arm
  gripper_group: ur5_gripper
  wrist_link: ur5_arm_ee_link
  gripper_link: ur5_arm_tcp_frame
  planner_service_name: /ur5_arm/path_planning/plan_kinematic_path
  trajectory_filter_service_name: /ur5_arm/trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: /ur5_arm/tabletop_segmentation
  singulation_segmentation_service_name: /ur5_arm/singulation/tabletop_segmentation
  recognition_service_name: /ur5_arm/mantis_object_recognition
  grasp_planning_service_name: /ur5_arm/plan_point_cluster_grasp
  planning_scene_service_name: /ur5_arm/environment_server/set_planning_scene_diff
  arm_inverse_kinematics_plugin: arm_kinematics_constraint_aware/KDLArmKinematicsPlugin
  joint_state_topic: /ur5_arm/joint_states
  joint_trajectory_service_name: /ur5_arm/joint_trajectory_action
  grasp_action_service_name: /ur5_arm/grasp_execution_action
 ######################### grasp pick and place parameters ########################
  pick_approach_distance: 0.10
  place_approach_distance: 0.10
  place_retreat_distance: 0.10
# ######################### grasp pick retry parameters ##########################
  pick_retry_attempts: 1
  pick_retry_offset: 0.03 # cm
  pick_retry_retreat_distance: 0.05
  attached_object_bb_side: 0.1 # 10cm
# ########################### place zone parameter ###############################
singulated_dropoff:
  frame_id: workcell_frame
  position:
    x: -0.30
    y: 0.60
    z: 0.12
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0.01
#  goal_candidates: 8
  next_location:
    generation_mode: 0
joint_home_position:
  side_position: [-1.20, -1.07948096023743, 1.67, -2.2049080765129627, -1.57, 0.05]
