COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\motoros_lib.mpLib motoros_lib.mpLib
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\motoros_lib.h motoros_lib.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\byte_array.h byte_array.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\log_wrapper.h log_wrapper.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\message_handler.h message_handler.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\shared_types.h shared_types.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_message.h simple_message.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_serialize.h simple_serialize.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_socket.h simple_socket.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\smpl_msg_connection.h smpl_msg_connection.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\tcp_server.h tcp_server.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\tcp_socket.h tcp_socket.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\typed_message.h typed_message.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\comms_fault_handler.h comms_fault_handler.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_data.h joint_data.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\message_manager.h message_manager.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\mp_default_main.h mp_default_main.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\ping_handler.h ping_handler.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\ros_conversion.h ros_conversion.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\simple_comms_fault_handler.h simple_comms_fault_handler.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_traj.h joint_traj.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\trajectory_job.h trajectory_job.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_traj_pt.h joint_traj_pt.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\joint_traj_pt_message.h joint_traj_pt_message.h
COPY ..\..\..\motoman\dx100\motoplus\motoros_lib\output\controller.h controller.h
COPY ..\include\longhorn\longhorn.h longhorn.h
COPY ..\include\longhorn\messages\gripper_message.h gripper_message.h
COPY ..\src\gripper_message.cpp gripper_message.cpp
