joint_limits:
  ur5_arm/shoulder_pan_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  ur5_arm/shoulder_lift_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  ur5_arm/elbow_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  ur5_arm/wrist_1_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  ur5_arm/wrist_2_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  ur5_arm/wrist_3_joint:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false