multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: Adept_Viper_s650_Link1
    child_frame_id: Adept_Viper_s650_Link1
groups:
  - name: manipulator
    base_link: Adept_Viper_s650_Link1
    tip_link: Adept_Viper_650_Interface_Plate
default_collision_operations:
  - object1: Adept_Viper_s650_Link1
    object2: Adept_Viper_s650_Link2
    operation: disable  # Adjacent in collision
  - object1: Adept_Viper_s650_Link2
    object2: Adept_Viper_s650_Link3
    operation: disable  # Adjacent in collision
  - object1: Adept_Viper_s650_Link3
    object2: Adept_Viper_s650_Link4
    operation: disable  # Adjacent in collision
  - object1: Adept_Viper_s650_Link4
    object2: Adept_Viper_s650_Link5
    operation: disable  # Adjacent in collision
  - object1: Adept_Viper_s650_Link5
    object2: Adept_Viper_s650_Link6
    operation: disable  # Adjacent in collision
  - object1: Adept_Viper_s650_Link6
    object2: Adept_Viper_650_Interface_Plate
    operation: disable  # Adjacent in collision
  - object1: Adept_Viper_650_Interface_Plate
    object2: Adept_Viper_s650_Link3
    operation: disable  # Never in collision
  - object1: Adept_Viper_650_Interface_Plate
    object2: Adept_Viper_s650_Link4
    operation: disable  # Never in collision
  - object1: Adept_Viper_s650_Link1
    object2: Adept_Viper_s650_Link3
    operation: disable  # Never in collision
  - object1: Adept_Viper_s650_Link3
    object2: Adept_Viper_s650_Link6
    operation: disable  # Never in collision
  - object1: Adept_Viper_s650_Link4
    object2: Adept_Viper_s650_Link6
    operation: disable  # Never in collision