manipulator:
  kinematics_solver: longhorn_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  redundancy:
    name: joint_e
  tip_name: link_t
  root_name: base_link
