base_link: base_link

sensors:

  chains:
    arm_chain:
      root: base_link
      tip: palm
      cov:
       joint_angles: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      gearing: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  rectified_cams:
    kinect_camera:
      frame_id: kinect_rgb_optical_frame
      baseline_shift: 0.0
      baseline_rgbd: 0.055
      f_shift: 0.0
      cx_shift: 0.0
      cy_shift: 0.0
      cov: {u: 0.25, v: 0.25, x: 0.25}

  tilting_lasers: {}

checkerboards:
  small_cb_4x5:
    corners_x: 4
    corners_y: 5
    spacing_x: 0.0245
    spacing_y: 0.0245

transforms:
  arm_chain_cb:   [ 0, 0, 0.125, 0, -pi/2, 0]

