
# ----- Tilting Laser -----
# Right now, laser reconfig is unimplemented. We work
# around this by creating multiple laser sensors that
# all use the same laser data, but process the data
# with different params defined in the processing
# nodes themselves.

tilt_laser:
  laser_cb_detector_config:  /none
  configs: []

tilt_laser_8x6:
  laser_cb_detector_config:  /none
  configs: []

tilt_laser_7x6:
  laser_cb_detector_config:  /none
  configs: []
