<?xml version="1.0" ?>
<robot name="mantis_ur5" xmlns:xacro="http://ros.org/wiki/xacro">
	<include filename="$(find mantis_config)/urdf/vacuum_gripper_macro.xacro"/>
	<include filename="$(find ur5_description)/urdf/gazebo.urdf.xacro" />
  	<include filename="$(find ur5_description)/urdf/model.urdf.xacro" />	
	<include filename="$(find mantis_config)/urdf/mantis_workspace_components.xacro"/>
	<include filename="$(find mantis_config)/urdf/mantis_sensor_macro.xacro"/>

	<!-- property list -->
	<xacro:property name="workcell_height" value="1"/>
	<xacro:property name="robot_stand_height" value="0.20"/>
	<xacro:property name="vacuum_gripper_width" value="0.088"/>
	<xacro:property name="arm2_prefix" value="ur5_arm_"/>
	<xacro:property name="arm2_name" value="ur5"/>	

	<!-- instantiating arm and gripper -->	
	<xacro:ur5_robot prefix="${arm2_prefix}"/>
	<xacro:vacuum_gripper_definition prefix="${arm2_prefix}"/>

	<!-- instantiating workcell definitions -->
	<xacro:workcell_zone2_components/>
	<!-- end of workcell definitions -->

	<!-- instantiating sensor definitions -->
	<xacro:sensor_definitions prefix="${arm2_prefix}" parent_link="${arm2_prefix}base_link" 
		x_val="1.08" y_val="-0.72" z_val="${0.82 - robot_stand_height}" pitch="0.5235" yaw="2.536"/>
	<!-- end of sensor definitions -->

	<!-- arm-workcell link definitions -->
	<link name="ur5_stand">
		<visual>
			<geometry>
				<cylinder radius="0.0735" length="${robot_stand_height}"/>
			</geometry>
			<material name="orange_transparent"/>
		</visual>
		<collision>
			<geometry>
				<cylinder radius="0.0735" length="${robot_stand_height}"/>
			</geometry>
			<material name="blue_transparent"/>
		</collision>
	</link>
	<joint name="workcell_to_stand" type="fixed">
		<parent link="workcell_frame"/>
		<child link="ur5_stand"/>
		<origin xyz="-0.238 0 0.10"/>
	</joint>
	<!-- end of arm-workcell link definitions -->

	<!-- arm-workcell joint definitions -->
	<joint name="${arm2_name}_to_stand" type="fixed">
		<parent link="ur5_stand"/>
		<child link="${arm2_prefix}base_link"/>
		<origin xyz="0 0 0.10" rpy="0 0 -3.14"/>
	</joint>
		
	<!-- end of arm workcell joint definitions-->

	<!-- arm-gripper coupling joint definitions -->
	<joint name="${arm2_prefix}to_gripper" type="fixed">
		<parent link="${arm2_prefix}ee_link"/>
		<child link="${arm2_prefix}gripper_frame"/>
		<origin xyz="0 0 0" rpy="0 1.57 0"/>
	</joint>
	<!-- end of arm-gripper coupling joint definitions -->
</robot>
