<?xml version="1.0" ?>
<robot name="mantis_ur5" xmlns:xacro="http://ros.org/wiki/xacro">
	<include filename="$(find mantis_config)/urdf/vacuum_gripper_macro.xacro"/>
	<include filename="$(find ur5_description)/urdf/gazebo.urdf.xacro" />
  	<include filename="$(find ur5_description)/urdf/model.urdf.xacro" />	
	<include filename="$(find mantis_config)/urdf/mantis_workspace_components.xacro"/>
	<include filename="$(find mantis_config)/urdf/mantis_sensor_macro.xacro"/>

	<!-- property list -->
	<xacro:property name="workcell_height" value="1"/>
	<xacro:property name="robot_stand_height" value="0.20"/>
	<xacro:property name="vacuum_gripper_width" value="0.088"/>
	<xacro:property name="arm_prefix" value="ur5_arm_"/>
	<xacro:property name="arm_name" value="ur5"/>	
	<xacro:property name="temp_base_offset" value="0.0"/>

	<!-- instantiating arm and gripper -->	
	<xacro:ur5_robot prefix="${arm_prefix}"/>
	<xacro:vacuum_gripper_definition prefix="${arm_prefix}"/>

	<!-- instantiating workcell definitions -->
	<xacro:workcell_zone2_components/>
	<!-- end of workcell definitions -->

	<!-- arm-workcell link definitions -->
	<link name="ur5_stand">
		<visual>
			<geometry>
				<cylinder radius="0.0735" length="${robot_stand_height}"/>
			</geometry>
			<material name="orange_transparent"/>
		</visual>
		<collision>
			<geometry>
				<cylinder radius="0.0735" length="${robot_stand_height}"/>
			</geometry>
			<material name="blue_transparent"/>
		</collision>
	</link>

	<!-- instantiating sensor definitions -->
	<xacro:sensor_definitions prefix="${arm_prefix}" parent_link="ur5_stand" 
		x_val="-.849" y_val="0.18" z_val="1.083" pitch="1.175" yaw="0.0" roll="0.004" /> 
	<!--xacro:sensor_definitions prefix="${arm_prefix}" parent_link="${arm_prefix}base_link" 
		x_val="1.08" y_val="-0.72" z_val="${0.82 - robot_stand_height}" pitch="0.5235" yaw="2.536"/-->
	<!-- end of sensor definitions -->

	<joint name="workcell_to_stand" type="fixed">
		<parent link="workcell_frame"/>
		<child link="ur5_stand"/>
		<origin xyz="-0.238 0 ${robot_stand_height * 0.5}"/>
	</joint>
	<!-- end of arm-workcell link definitions -->

	<!-- arm-workcell joint definitions -->
	<joint name="${arm_name}_to_stand" type="fixed">
		<parent link="ur5_stand"/>
		<child link="${arm_prefix}base_link"/>
		<origin xyz="0 0 ${robot_stand_height * 0.5 + temp_base_offset}" rpy="0 0 2.355"/>
	</joint>
		
	<!-- end of arm workcell joint definitions-->

	<!-- arm-gripper coupling joint definitions -->
	<joint name="${arm_prefix}to_gripper" type="fixed">
		<parent link="${arm_prefix}ee_link"/>
		<child link="${arm_prefix}gripper_frame"/>
		<origin xyz="0 0 0" rpy="-1.57 0 -1.57"/> <!-- 0 1.57 0 -->
	</joint>
	<!-- end of arm-gripper coupling joint definitions -->
</robot>
