joint_trajectory_action:
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  constraints:
    goal_time: 0.3
    joint_s:
      goal: 0.04
    joint_l:
      goal: 0.04
    joint_e:
      goal: 0.04
    joint_u:
      goal: 0.04
    joint_r:
      goal: 0.04
    joint_b:
      goal: 0.04
    joint_t:
      goal: 0.04
