collision_clearance: 0.05

collision_links:
  sia20d_arm/base_link
  sia20d_arm/link_s
  sia20d_arm/link_l
  sia20d_arm/link_e
  sia20d_arm/link_u
  sia20d_arm/link_r
  sia20d_arm/link_b
  sia20d_arm/link_t
  sia20d_arm/palm
  coupler
  table_base1
  back_wall1
  front_wall1
  left_wall1
  right_wall1
  sia20d_arm/kinect_keepout

joint_costs:
  sia20d_arm/joint_s: 1.0
  sia20d_arm/joint_l: 1.0
  sia20d_arm/joint_e: 1.0
  sia20d_arm/joint_u: 1.0
  sia20d_arm/joint_r: 1.0
  sia20d_arm/joint_b: 1.0
  sia20d_arm/joint_t: 1.0

joint_velocity_limits:
  sia20d_arm/joint_s: 0.5
  sia20d_arm/joint_l: 0.5
  sia20d_arm/joint_e: 0.5
  sia20d_arm/joint_u: 0.5
  sia20d_arm/joint_r: 0.5
  sia20d_arm/joint_b: 0.5
  sia20d_arm/joint_t: 0.5


reference_frame: workcell_frame

collision_space:
  #size_x: 3.0
  #size_y: 4.0
  #size_z: 2.2
  size_x: 4.0
  size_y: 4.0
  size_z: 4.0
  #origin_x: -1.0
  #origin_y: -2.0
  #origin_z: -0.3
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  resolution: 0.02
  field_bias_x: 0.0
  field_bias_y: 0.0
  field_bias_z: 0.0
      
chomp_collision_operations:
  - object1: workcell_frame
    object2: sia20d_arm/kinect
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/kinect_frame
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/kinect_ir_optical_frame
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/kinect_rgb_optical_frame
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: sia20d_arm/base_link
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/link_s
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_s
    object2: sia20d_arm/link_l
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_l
    object2: sia20d_arm/link_e
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_e
    object2: sia20d_arm/link_u
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_u
    object2: sia20d_arm/link_r
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_r
    object2: sia20d_arm/link_b
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_b
    object2: sia20d_arm/link_t
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/link_t
    object2: sia20d_arm/coupler
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/palm
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: back_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: front_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: left_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: right_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: table_base1
    operation: disable  # Adjacent in collision
  - object1: back_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: left_wall1
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: right_wall1
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: sia20d_arm/kinect
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: left_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: right_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: sia20d_arm/base_link
    object2: table_base1
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect_keepout
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Always in collision
  - object1: sia20d_arm/kinect_keepout
    object2: table_base1
    operation: disable  # Always in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/kinect
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/kinect_frame
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_b
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_r
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_t
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_u
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/palm
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_b
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_r
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_t
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/palm
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/palm
    operation: disable  # Occasionally in collision
  - object1: back_wall1
    object2: front_wall1
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: left_wall1
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: right_wall1
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/base_link
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/kinect
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/base_link
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: right_wall1
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/base_link
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/kinect
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/base_link
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/kinect
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/kinect
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/kinect_frame
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/kinect_keepout
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/kinect_rgb_link
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/base_link
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/kinect_ir_link
    operation: disable  # Never in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/link_b
    operation: disable  # Never in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm/coupler
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_frame
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_frame
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_b
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_ir_link
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_keepout
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_keepout
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_keepout
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_keepout
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_b
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/kinect_rgb_link
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_b
    object2: sia20d_arm/link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_b
    object2: sia20d_arm/link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_b
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_b
    object2: sia20d_arm/palm
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_e
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_e
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_e
    object2: sia20d_arm/link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_e
    object2: sia20d_arm/palm
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_e
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_l
    object2: sia20d_arm/link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_l
    object2: sia20d_arm/link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_l
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_l
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_r
    object2: sia20d_arm/link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_r
    object2: sia20d_arm/link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_r
    object2: sia20d_arm/palm
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_s
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_s
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_t
    object2: sia20d_arm/link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_t
    object2: sia20d_arm/palm
    operation: disable  # Never in collision
  - object1: sia20d_arm/link_u
    object2: sia20d_arm/palm
    operation: disable  # Never in collision
