joint_limits:
  sia20d_arm_joint_s:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sia20d_arm_joint_l:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.26
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sia20d_arm_joint_e:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sia20d_arm_joint_u:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sia20d_arm_joint_r:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sia20d_arm_joint_b:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  sia20d_arm_joint_t:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 6.97
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
