multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: workcell_frame
    child_frame_id: workcell_frame
groups:
  - name: sia20d_arm
    base_link: sia20d_arm_base_link
    tip_link: sia20d_arm_link_t
  - name: sia20d_gripper
    joints:
      - tool-coupler
      - coupler-hand
default_collision_operations:
  - object1: workcell_frame
    object2: sia20d_arm_kinect
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_kinect_frame
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_kinect_ir_optical_frame
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_kinect_rgb_optical_frame
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: sia20d_arm_base_link
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_link_s
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_s
    object2: sia20d_arm_link_l
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_l
    object2: sia20d_arm_link_e
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_e
    object2: sia20d_arm_link_u
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_u
    object2: sia20d_arm_link_r
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_r
    object2: sia20d_arm_link_b
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_b
    object2: sia20d_arm_link_t
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_link_t
    object2: sia20d_arm_coupler
    operation: disable  # Adjacent in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_palm
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: back_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: front_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: left_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: right_wall1
    operation: disable  # Adjacent in collision
  - object1: workcell_frame
    object2: table_base1
    operation: disable  # Adjacent in collision
  - object1: back_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: left_wall1
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: right_wall1
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: sia20d_arm_kinect
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Always in collision
  - object1: front_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: left_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: right_wall1
    object2: table_base1
    operation: disable  # Always in collision
  - object1: sia20d_arm_base_link
    object2: table_base1
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect_keepout
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Always in collision
  - object1: sia20d_arm_kinect_keepout
    object2: table_base1
    operation: disable  # Always in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_kinect
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_kinect_frame
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_b
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_r
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_t
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_u
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_palm
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_b
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_r
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_t
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_palm
    operation: disable  # Occasionally in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_palm
    operation: disable  # Occasionally in collision
  - object1: back_wall1
    object2: front_wall1
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: left_wall1
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: right_wall1
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_base_link
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_kinect
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_kinect_frame
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Never in collision
  - object1: back_wall1
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_base_link
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_kinect_frame
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: front_wall1
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: right_wall1
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_base_link
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_kinect
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_kinect_frame
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: left_wall1
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_base_link
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_kinect
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_kinect_frame
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: right_wall1
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_kinect
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_kinect_frame
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_kinect_keepout
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_kinect_rgb_link
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_base_link
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_kinect_ir_link
    operation: disable  # Never in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_link_b
    operation: disable  # Never in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm_coupler
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_frame
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_frame
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_b
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_ir_link
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_keepout
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_keepout
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_keepout
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_keepout
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_b
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_kinect_rgb_link
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_b
    object2: sia20d_arm_link_e
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_b
    object2: sia20d_arm_link_l
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_b
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_b
    object2: sia20d_arm_palm
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_e
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_e
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_e
    object2: sia20d_arm_link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_e
    object2: sia20d_arm_palm
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_e
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_l
    object2: sia20d_arm_link_r
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_l
    object2: sia20d_arm_link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_l
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_l
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_r
    object2: sia20d_arm_link_s
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_r
    object2: sia20d_arm_link_t
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_r
    object2: sia20d_arm_palm
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_s
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_s
    object2: table_base1
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_t
    object2: sia20d_arm_link_u
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_t
    object2: sia20d_arm_palm
    operation: disable  # Never in collision
  - object1: sia20d_arm_link_u
    object2: sia20d_arm_palm
    operation: disable  # Never in collision
