navigator:
  arm_group: sia20d_arm
  gripper_group: sia20d_gripper
  wrist_link: sia20d_arm_link_t
  gripper_link: sia20d_arm_tcp_frame
  planner_service_name: /sia20d_arm/path_planning/plan_kinematic_path
  trajectory_filter_service_name: /sia20d_arm/trajectory_filter_server/filter_trajectory_with_constraints
  segmentation_service_name: /sia20d_arm/tabletop_segmentation
  recognition_service_name: /sia20d_arm/mantis_object_recognition
  grasp_planning_service_name: /sia20d_arm/plan_point_cluster_grasp
  planning_scene_service_name: /sia20d_arm/environment_server/set_planning_scene_diff
  arm_inverse_kinematics_plugin: SIA20D_Mesh_manipulator_kinematics/IKFastKinematicsPlugin
  joint_state_topic: /sia20d_arm/joint_states
  joint_trajectory_service_name: /sia20d_arm/joint_trajectory_action
  grasp_action_service_name: /sia20d_arm/grasp_execution_action
  num_of_grasp_attempts: 6
  offset_from_first_grasp: 0.02 #1cm
  attached_object_bb_side: 0.1 #10cm
cluttered_dropoff:
  frame_id: sia20d_arm_base_link
  position:
    x: 0.10
    y: -0.6
    z: 0.2
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0
  next_location:
    generation_mode: 0
    min_spacing: 0.05 # meters (ignored if using generation mode 0)
    max_spacing: 0.08 # meters (ignored if using generation mode 0)
    place_region_radius: 0.2 # meters (ignored if using generation mode 0)
singulated_dropoff:
  frame_id: sia20d_arm_base_link
  position:
    x: 0.10
    y: -0.6
    z: 0.2
  orientation:
    axis:
      x: 0
      y: 0
      z: 1
    angle: 0
  next_location:
    generation_mode: 0
    min_spacing: 0.05 # meters (ignored if using generation mode 0)
    max_spacing: 0.08 # meters (ignored if using generation mode 0)
    place_region_radius: 0.2 # meters (ignored if using generation mode 0)
joint_home_position:
  side_position: [-1.10, 0.68, 2.46, 1.25, -0.41, 1.34,1.14]
