pick_zones:
 - zone_name: zone_1
   x_min: 0.45
   x_max: 1.2
   y_min: -0.88
   y_max: 0.0
   frame_id: workcell_frame
 - zone_name: zone_2
   x_min: 0.45
   x_max: 1.2
   y_min: 0.01
   y_max: 0.88
   frame_id: workcell_frame
place_zones:
 - zone_name: place_zone1_a
   x_min: 0.45
   x_max: 0.8
   y_min: 0.01
   y_max: 0.50
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.01
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [1,3,5]
 - zone_name: place_zone1_b
   x_min: 0.801
   x_max: 1.2
   y_min: 0.01
   y_max: 0.88
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.01
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [0,2]
 - zone_name: place_zone1_c
   x_min: 0.45
   x_max: 0.80
   y_min: 0.51
   y_max: 0.88
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.01
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [4]
 - zone_name: place_zone2_a
   x_min: 0.45
   x_max: 0.80
   y_min: -0.88
   y_max: 0.00
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.01
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [1,3,5]
 - zone_name: place_zone2_b
   x_min: 0.801
   x_max: 1.2
   y_min: -0.88
   y_max: 0.00
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: 0.01
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [0,2,4]
