pick_zones:
 - zone_name: singulated_zone
   x_min: 0.6
   x_max: 1.2
   y_min: -0.88
   y_max: -0.201
   frame_id: workcell_frame
 - zone_name: sorted_zone
   x_min: 0.6
   x_max: 1.2
   y_min: -0.20
   y_max: 0.7
   frame_id: workcell_frame
place_zones:
 - zone_name: place_zone1_a
   x_min: 0.6
   x_max: 0.85
   y_min: -0.20
   y_max: 0.35
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [0,2]
 - zone_name: place_zone1_b
   x_min: 0.851
   x_max: 1.2
   y_min: -0.20
   y_max: 0.7
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 2
   ids_allowed: [1,3,5]
 - zone_name: place_zone1_c
   x_min: 0.6
   x_max: 0.85
   y_min: 0.351
   y_max: 0.7
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [4]
 - zone_name: place_zone2_a
   x_min: 0.6
   x_max: 0.85
   y_min: -0.88
   y_max: -0.201
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [1,3,5]
 - zone_name: place_zone2_b
   x_min: 0.851
   x_max: 1.2
   y_min: -0.88
   y_max: -0.201
   frame_id: workcell_frame
   pose_candidates: 8
   orientation_axis:
    x: 0.0
    y: 0.0
    z: 1.0
   release_distance: -0.02
   next_location:
    min_spacing: 0.16
    max_spacing: 0.20
    generation_mode: 0
   ids_allowed: [0,2,4]
