joint_limits:
  joint_1:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.8798
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_2:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.8798
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_3:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.0543
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_4:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_5:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 5.9341
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_6:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 9.0757
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false