#params for the gripper model/grasp search

#the axis-aligned model of the gripper for checking for collisions and points in the hand
gripper_boxes: [[[0.090, -0.1005, -0.0175], [0.160, -0.045, 0.0175]], 
               [[0.160, -0.1005, -0.0175], [0.210, -0.0675, 0.0175]],
               [[0.090, 0.045, -0.0525], [0.16, 0.1005, 0.0525]], 
               [[0.160, 0.0675, -0.0525], [0.210, 0.1005, 0.0525]],
               [[0.0, -0.1005, -0.065], [0.09, 0.1005, 0.065]]]

space_boxes: [[[[0.160, -0.0675, -0.0175], [0.210, 0.0675, 0.0175]], [[0.090, -0.045, -0.0175],[0.160, 0.045, 0.0175]]],
              [[[0.160, 0.0, 0.0175], [0.210, 0.0675, 0.0525]], [[0.090, 0.0, 0.0175],[0.160, 0.045, 0.0525]]],
              [[[0.160, 0.0, -0.0525], [0.210, 0.0675, -0.0175]], [[0.090, 0.0, -0.0525],[0.160, 0.045, -0.0175]]]]

# joint related param values
joint_names: 
  manipulator: ["joint_1", "joint_2", "joint_3"]

pregrasp_joint_angles: 
  manipulator: [0.0,0.0,0.0]
grasp_joint_angles: 
  manipulator: [0.0,0.0,0.0]
pregrasp_joint_efforts: 
  manipulator: [0.0,0.0,0.0]
grasp_joint_efforts: 
  manipulator: [0.0,0.0,0.0]

#the actual desired wrist frame of the robot (4x4, column-order) in the gripper model frame
actual_wrist_frame_in_model_frame: [[0.0,-1.0,0.0,0.0],[0.0,0.0,-1.0,0.0],[1.0,0.0,0.0,0.0],[0.14113,0.0,0.0,1.0]]

#default pregrasp dist away from grasp (overridden if pregrasp_just_outside_box is True)
default_pregrasp_dist: 0.21

#minimum number of points to be declared a good grasp
min_good_grasp_points: 15.

#distance from the wrist frame to the center of the fingertips (along the gripper x-axis)
wrist_to_fingertip_dist: 0.225

#distance from the wrist frame to a safe distance barely past the surface of the palm (along the gripper x-axis)
wrist_to_palm_dist: 0.09

#bounding box "fits in hand" if the relevant dimension is less than this
gripper_opening: 0.165

#only want side grasps if the bounding box height is greater than this
height_good_for_side_grasps: 0.11

#start the side grasp search at this height or at the center of the object, whichever is higher
side_grasp_start_height: 0.075

#how far to move the gripper to the side with each step when searching for grasps (default value)
side_step: 0.02

#how far to move the palm inward with each step when searching for grasps (default value)
palm_step: 0.05

#set this to true to limit the planner to overhead grasps
overhead_grasps_only: True

#set this to true to limit the planner to side grasps(default value)
side_grasps_only: False

#set this to false to omit random high-point grasps(default value)
include_high_point_grasps: True

#set this to true to make the pregrasps be just outside the bounding box instead of self.pregrasp_dist away from the grasp(default value)
pregrasp_just_outside_box: False

#how many backing-off-from-the-deepest-possible-grasp grasps to keep for each good grasp found (default value)
backoff_depth_steps: 5

#don't check the neighbors for each grasp (reduces grasps checked, but makes for worse rankings) (default value)
disable_grasp_neighbor_check: False

