multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: end_effector
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
      - Joint_6
  - name: manipulator
    base_link: base_link
    tip_link: Link_6
default_collision_operations:
  - object1: base_link
    object2: Link_1
    operation: disable  # Adjacent in collision
  - object1: Link_1
    object2: Link_2
    operation: disable  # Adjacent in collision
  - object1: Link_2
    object2: Link_3
    operation: disable  # Adjacent in collision
  - object1: Link_3
    object2: Link_4
    operation: disable  # Adjacent in collision
  - object1: Link_4
    object2: Link_5
    operation: disable  # Adjacent in collision
  - object1: Link_5
    object2: Link_6
    operation: disable  # Adjacent in collision
  - object1: Link_6
    object2: tool0
    operation: disable  # Adjacent in collision
  - object1: Link_1
    object2: Link_3
    operation: disable  # Never in collision
  - object1: Link_2
    object2: Link_4
    operation: disable  # Never in collision
  - object1: Link_2
    object2: Link_5
    operation: disable  # Never in collision
  - object1: Link_2
    object2: Link_6
    operation: disable  # Never in collision
  - object1: Link_2
    object2: base_link
    operation: disable  # Never in collision
  - object1: Link_3
    object2: Link_5
    operation: disable  # Never in collision
  - object1: Link_3
    object2: Link_6
    operation: disable  # Never in collision
  - object1: Link_3
    object2: base_link
    operation: disable  # Never in collision