plug_pick_point_z: 0.047
enc_pick_point_z: 0.058
pvct_pick_point_z: 0.025
plug_offset_x: 0.009
plug_offset_y: 0.00
plug_offset_z: 0.028
enclosure_offset_x: 0.00563
enclosure_offset_y: -0.0044
enclosure_offset_z: 0.049
pvct_offset_x: 0.0034
pvct_offset_y: -0.0019
pvct_offset_z: 0.012
