joint_limits:
  joint_1:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    angle_wraparound: false
    max_velocity: 2.8
    max_acceleration: 1
  joint_2:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    angle_wraparound: false
    max_velocity: 2.8
    max_acceleration: 1
  joint_3:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    angle_wraparound: false
    max_velocity: 3.0
    max_acceleration: 1
  joint_4:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    angle_wraparound: false
    max_velocity: 6.1
    max_acceleration: 1
  joint_5:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    angle_wraparound: false
    max_velocity: 5.9
    max_acceleration: 1
  joint_6:
    has_position_limits: true
    has_velocity_limits: true
    has_acceleration_limits: true
    angle_wraparound: false
    max_velocity: 9.0
    max_acceleration: 1
