arm1_marker:
  frame_id: workcell_frame
  namespace: ur5
  text: idle
  text_size: 0.1
  id: 1
  position:
    x: -1.0
    y: 0.0
    z: 1.2
  color:
    r: 1.0
    g: 1.0
    b: 1.0
    a: 1.0
arm2_marker:
  frame_id: workcell_frame
  namespace: sia20d
  text: idle
  text_size: 0.1
  id: 2
  position:
    x: 1.0
    y: 0.0
    z: 1.2
  color:
    r: 1.0
    g: 1.0
    b: 1.0
    a: 1.0
